### ISSUE TITLE
Use with Renesas S7G2

### ISSUE THREAD

**Issue by RajaSrinivasan** [simonjwright/cortex-gnat-rts#42]
would like to use this for experimenting with the Renesas S7G2. It has an M4 core.

curious what it would take to adapt to the above?

2 Questions:

- Currently using the ThreadX infrastructure. Ideally I can build ada routines I can plug into an existing C/C++ application.
- Alternatively - move to FreeRTOS infrastructure. but I would need the Ethernet subsystem support

Any pointers?

**Comment by simonjwright** [comment]
On 27 Nov 2022, at 11:29, RajaSrinivasan ***@***.***> wrote:
> 
> would like to use this for experimenting with the Renesas S7G2. It has an M4 core.
> curious what it would take to adapt to the above?
> 
> 2 Questions:
> 
> Currently using the ThreadX infrastructure. Ideally I can build ada routines I can plug into an existing C/C++ application.
I’d have thought this could be fairly straightforward, so long as you didn’t want to use any Ada tasking; which would mean not using this work at all.

I think what you’d need would be what used to be called a 'zero-footprint' option, now I believe 'light'. You wouldn’t want your Ada to be the main program, so you’d build a library/libraries and call from C/C++, avoiding any need to initialise the board.

The build process for this is in flux just at the moment. Be prepared to be baffled at https://github.com/alire-project/GNAT-FSF-builds <https://github.com/alire-project/GNAT-FSF-builds>.
> Alternatively - move to FreeRTOS infrastructure. but I would need the Ethernet subsystem support
Given Cortex-M4 I’d expect the only necessary work would be to amend the startup code as required, specifically the clocks and memory initialisation. The Renesas SDK would give good clues about startup.

FreeRTOS does have ethernet support, but how difficult it would be to adapt to your board I don’t know. Perhaps ask in the FreeRTOS forums? (https://forums.freertos.org <https://forums.freertos.org/>)

**Comment by simonjwright** [comment]
Closing because no action required.
